<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>p8</string>
    <string>prog8</string>
   </array>
  <key>name</key>
  <string>prog8</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.prog8</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#meta</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\w+\s*)(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.namespace.prog8</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\w+\s*)(\$[\da-fA-F]+\s*)(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.namespace.prog8</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.integer.hexadecimal.prog8</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>assembler</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(adc|and|asl|bcc|bcs|beq|bit|bmi|bne|bpl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|inc|inx|iny|jmp|jsr|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|rti|rts|sbc|sec|sed|sei|sta|stx|sty|tax|tay|tsx|txa|txs|tya|bra|brl|cop|jml|jsl|mvn|mvp|pea|pei|per|phb|phd|phk|phx|phy|plb|pld|plx|ply|rep|rtl|sep|stp|stz|tcd|tcs|tdc|trb|tsb|tsc|txy|tyx|wai|wdm|xba|xce|ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRK|BVC|BVS|CLC|CLD|CLI|CLV|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JSR|LDA|LDX|LDY|LSR|NOP|ORA|PHA|PHP|PLA|PLP|ROL|ROR|RTI|RTS|SBC|SEC|SED|SEI|STA|STX|STY|TAX|TAY|TSX|TXA|TXS|TYA|BRA|BRL|COP|JML|JSL|MVN|MVP|PEA|PEI|PER|PHB|PHD|PHK|PHX|PHY|PLB|PLD|PLX|PLY|REP|RTL|SEP|STP|STZ|TCD|TCS|TDC|TRB|TSB|TSC|TXY|TYX|WAI|WDM|XBA|XCE)\b)</string>
          <key>name</key>
          <string>support.function.prog8</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\;)(.+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.prog8</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>comment.line.prog8</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>constant</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\btrue|false|void\b)</string>
          <key>name</key>
          <string>constant.language.prog8</string>
        </dict>
       </array>
    </dict>
    <key>general</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(^\s*)(\%asm)(\s*{{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.directive.prog8</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#general__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(}})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#general__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.prog8</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#general__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keywords</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#storage</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#constant</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#support</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#label</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#meta</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\w+)(\s*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.prog8</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#general__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#section</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#variable</string>
        </dict>
       </array>
    </dict>
    <key>general__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#assembler</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#label</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#section</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#variable</string>
        </dict>
       </array>
    </dict>
    <key>general__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#general</string>
        </dict>
       </array>
    </dict>
    <key>general__3</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>general__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#general</string>
        </dict>
       </array>
    </dict>
    <key>general__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#general</string>
        </dict>
       </array>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(sub|if|if_cs|if_cc|if_eq|if_ne|if_pl|if_mi|if_vs|if_vc|if_z|if_nz|if_pos|if_neg|for|in|to|step|do|while|until|repeat|else|when|return|break|as|goto|asmsub|clobbers)\b)</string>
          <key>name</key>
          <string>keyword.control.prog8</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(and|or)\b)</string>
          <key>name</key>
          <string>keyword.operator.prog8</string>
        </dict>
       </array>
    </dict>
    <key>label</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(^\s*\w+\:)</string>
          <key>name</key>
          <string>entity.name.label.prog8</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#general</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#general</string>
        </dict>
       </array>
    </dict>
    <key>meta</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(^\s*)(%)([a-zA-Z]+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.prog8</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>meta.directive.prog8</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.control.directive.prog8</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.integer.prog8</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-?\d+\.\d+e?\d+)</string>
          <key>name</key>
          <string>constant.numeric.float.prog8</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$[\da-fA-F]+)</string>
          <key>name</key>
          <string>constant.numeric.integer.hexadecimal.prog8</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\%[0-1]+)</string>
          <key>name</key>
          <string>constant.numeric.integer.binary.prog8</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\&apos;.\&apos;)</string>
          <key>name</key>
          <string>constant.numeric.integer.prog8</string>
        </dict>
       </array>
    </dict>
    <key>section</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\w+\.)</string>
          <key>name</key>
          <string>entity.name.namespace.prog8</string>
        </dict>
       </array>
    </dict>
    <key>storage</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(ubyte|byte|word|uword|float|str)\b)</string>
          <key>name</key>
          <string>storage.type.prog8</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(const)\b)</string>
          <key>name</key>
          <string>storage.modifier.prog8</string>
        </dict>
       </array>
    </dict>
    <key>support</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b(abs|atan|ceil|cos|cos8u|cos8|cos16u|cos16|deg|floor|ln|log2|rad|round|sin|sgn|sin8u|sin8|sin16u|sin16|sqrt16|sqrt|tan|any|all|len|max|min|reverse|sum|sort|memcopy|memset|memsetw|leftstr|rightstr|strlen|strcmp|substr|exit|lsb|msb|mkword|rnd|rndw|rndf|rol|rol2|ror|ror2|rsave|rrestore|read_flags|sizeof|set_carry|clear_carry|set_irqd|clear_irqd|swap)\b)</string>
          <key>name</key>
          <string>support.function.prog8</string>
        </dict>
       </array>
    </dict>
    <key>variable</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\w+\b)</string>
          <key>name</key>
          <string>variable.other.prog8</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
